models/Reward.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * Class Reward
 * @package app\models
 *
 * @property int $id
 * @property int $type
 * @property string $title
 * @property int $exchange_reward_id
 * @property int $exchange_ratio
 * @property int $stock
 * @property int $transaction_limit
 * @property int $date_created
 *
 */
class Reward extends ActiveRecord
{
    /** @var int */
    private $withdrawal= null;

    const TYPE_MONEY = 10;
    const TYPE_SCORE = 20;
    const TYPE_GIFT = 30;

    const TYPE_MONEY_TEXT = 'Money';
    const TYPE_SCORE_TEXT = 'Score';
    const TYPE_GIFT_TEXT = 'Gift';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reward';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['type'], 'required'],
            [['id', 'type', 'exchange_reward_id', 'exchange_ratio', 'stock', 'date_created', 'transaction_limit'], 'integer', 'min' => 0],
            [['title'], 'string'],
            [['exchange_reward_id'], 'validateExchange']
        ];

    }

    public function validateExchange($attribute): bool
    {
        $exchange_reward = Reward::findOne($this->exchange_reward_id);
        if (!$exchange_reward) {
            $this->addError($attribute, 'Does not exist');

            return false;
        }

        if ($exchange_reward->type === $this->type) {
            $this->addError($attribute, 'Invalid exchange reward type');

            return false;
        }

        return true;
    }

    public function beforeSave($insert)
    {
        $this->date_created = $this->date_created ?? time();

        return parent::beforeSave($insert);
    }

    public function getRandomAmount():int
    {
        return rand(1, $this->getAllowedAmount());
    }

    /**
     * @param int|null $amount_requested
     * @return int
     */
    public function getAllowedAmount(int $amount_requested = null):int
    {
        if ($amount_requested && $amount_requested < $this->stock && $amount_requested < $this->transaction_limit) {

            return $amount_requested;
        }

        if ($this->stock !== null && $this->stock < $this->transaction_limit) {

            return $this->stock;
        }

        return $this->transaction_limit ;
    }

    public function isConvertible():bool
    {
        return !empty($this->exchange_ratio) && !empty($this->exchange_reward_id);
    }

    /**
     * @param int $amount
     * @return bool
     */
    public function decreaseStock(int $amount):bool
    {
        if ($this->stock === null) {
            return true;
        }

        $this->stock = $this->stock - $amount;

        return $this->save();

    }


    /**
     * @return Reward
     */
    public static function getRandomFromActiveRewards():? Reward
    {
        /** @var Reward[] $active_rewards */
        $active_rewards = Reward::find()
            ->where(['>', 'stock', 0])
            ->all();
        $rewards_count = count($active_rewards);

        if ($rewards_count <= 0) {

            return null;
        }

        return $active_rewards[rand(0, $rewards_count-1)];
    }

    public function setWithdrawal(int $amount):self
    {
        $this->withdrawal = $amount;
        return $this;
    }

    public function getWithdrawal():?int
    {
        return $this->withdrawal;
    }





}

controllers/RewardController.php
<?php

namespace app\controllers;

use app\models\Reward;
use app\models\User;
use app\models\UserRewardForm;
use Yii;
use yii\web\Controller;

class RewardController extends Controller
{
    /** @var User */
    private $user;

    public function beforeAction($action)
    {
        /** @var User $user */
        $this->user = Yii::$app->getUser()->identity;

        if (!$this->user) {
            $this->redirect('/');
        }

        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('reward_intro');
    }


    /**
     * Displays Random reward.
     *
     * @return string
     */
    public function actionShow()
    {
        $active_reward = Reward::getRandomFromActiveRewards();

        $user_reward_form = (new UserRewardForm())->setReward($active_reward);

        return $this->render('reward_form', [
            'user_reward_form' => $user_reward_form,
        ]);
    }

    public function actionGet()
    {
        $post = Yii::$app->request->post();

        if (!$post) {
            return $this->redirect('show');
        }

        $user_reward_form = new UserRewardForm();

        $transaction = Yii::$app->getDb()->beginTransaction();
        if ($user_reward_form->load($post) && $user_reward_form->submit()) {
            Yii::$app->session->setFlash('success', 'Got it!');
            $transaction->commit();
            return $this->redirect('/reward');
        }
        $transaction->rollBack();

        $message_type = 'error';
        Yii::$app->session->setFlash($message_type, "failed");

        return $this->redirect('/reward');
    }
}

views/reward/reward_form.php
<?php
use yii\bootstrap\ActiveForm;
use app\models\UserRewardForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $form yii\bootstrap\ActiveForm */
/* @var $this yii\web\View */
/* @var $user_reward_form UserRewardForm*/



$this->title = 'TAKE YR REWARD';
$this->params['breadcrumbs'][] = $this->title;
?>
    <h1 class="text-center"><?= Html::encode($this->title) ?></h1>

<br><br><br>

<?php $form = ActiveForm::begin([
        'action' => Url::to(['/reward/get'])
]); ?>

<div class="form-group text-center">
    <h3><?=$user_reward_form->getRewardText()?></h3>

    <?php if ($user_reward_form->isInStock()): ?>
        <?php if ($user_reward_form->getConversionText()): ?>

            <?= $form->field($user_reward_form, 'amount')->hiddenInput()->label(false);?>
            <?= $form->field($user_reward_form, 'reward_id')->hiddenInput()->label(false);?>
            <?= $form->field($user_reward_form, 'is_convert_to')->checkbox([
                'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            ])->label($user_reward_form->getConversionText()) ?>
        <?php endif;?>

        <?= Html::submitButton('Get reward', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        <a href="<?= Url::to('/reward/')?>">
            <?= Html::button('Dismiss', ['class' => 'btn btn-warning', 'name' => 'login-button']) ?>
        </a>
    <?php endif;?>

</div>


<?php ActiveForm::end(); ?>

views/reward/reward_intro.php
<?php
use yii\bootstrap\ActiveForm;
use app\models\UserRewardForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $form yii\bootstrap\ActiveForm */
/* @var $this yii\web\View */
/* @var $user_reward_form UserRewardForm*/



$this->title = 'REWARD?';
$this->params['breadcrumbs'][] = $this->title;
?>
    <h1 class="text-center"><?= Html::encode($this->title) ?></h1>

<br><br><br>


<div class="row"><div class="col-md-12 text-center">
        <a href="<?= Url::to('/reward/get')?>">
            <?= Html::button('Get it!', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </a>
</div>